### ISSUE TITLE
Kanban Board Set Up

### ISSUE THREAD

**Issue by ulisesedu7** [ulisesedu7/CapstoneProject2#1]
Hi Reviewer, 

We have a team of two people only (Addisu and Ulises). Here's the link:
https://github.com/users/ulisesedu7/projects/1

**Comment by BenMukebo** [comment]
### Hi Team,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Link to their GitHub project  ✔️   
- Information about the number of people in their group ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [x] Great job so far 👏🏻  however You have to make sure that all cards are assigned to team members. I'm supposed to see a circle with the user's avatar on each card. See the example below:


![image](https://user-images.githubusercontent.com/79058364/174669932-5bca7d06-ef7c-4d36-919d-343551f8c182.png)

- [x] make sure all Cards are assigned to team members in a fair way:
- You need to decide who is Student A, Student B. So each card with Student A in its title should always be assigned to the same student.
- All cards with group task in the title should be assigned to someone.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
Thanks for the feedback! All Changes have been applied here:
https://github.com/users/ulisesedu7/projects/1

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
